### ISSUE TITLE
"Two sum2- Input array sorted" typo for "right pointer" in step 5 of recommended solutions

### ISSUE THREAD

**Issue by AmirHossein-z** [sudheerj/datastructures-algorithms#10]
Hi. in the "Two sum2- Input array sorted" problem, step 5 of the recommended algorithm [link](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/2.twoSum2/twoSum2.md) says that the "right" pointer should be decremented but in solution [link](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/2.twoSum2/twoSum2.js), it implemented in such a way that "left" pointer is incremented. I think the recommended algorithm should be edited.

**Comment by sudheerj** [comment]
Thanks @AmirHossein-z for pointing it out. The documentation has been fixed. It should be left pointer.
