### ISSUE TITLE
Code Playgrounds

### ISSUE THREAD

**Issue by hatemhosny** [sudheerj/datastructures-algorithms#3]
Great work. Thank you!

I suggest adding playgrounds to allow trying out code, similar to [TheAlgorithms](https://the-algorithms.com/) website, which uses [LiveCodes](https://livecodes.io) (see [example](https://the-algorithms.com/playground?algorithm=binary-search&language=javascript)).

Please allow me to introduce [LiveCodes](https://livecodes.io), a [feature-rich](https://livecodes.io/docs/features/), [open-source](https://github.com/live-codes/livecodes), [client-side](https://livecodes.io/docs/why/#client-side), code playground that supports [80+ languages and frameworks](https://livecodes.io/docs/why/#language-support), including JS, TS, React, Vue, Svelte, Solid, Python, Go, Ruby, PHP and others (see [starter templates](https://livecodes.io/?new)). The [announcement post](https://blog.livecodes.io/introducing-livecodes/) gives a general overview.

Projects can be [shared](https://livecodes.io/docs/features/share/), [exported](https://livecodes.io/docs/features/export/) and [deployed](https://livecodes.io/docs/features/deploy/) (to GitHub Pages). Code can be [imported](https://livecodes.io/docs/features/import/) from many sources including GitHub.

LiveCodes is very [configurable](https://livecodes.io/docs/configuration/). Many of the features can be configured by [query parameters](https://livecodes.io/docs/configuration/query-params)

For example, to load the bubble sort algorithm from this URL:
```
https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/sorting/bubbleSortLinkedlist.js
```
Add it to the query parameter `x` like that, (also have the console open):

```
https://livecodes.io/?console=open&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/sorting/bubbleSortLinkedlist.js
```

[open in LiveCodes](https://livecodes.io/?console=open&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/sorting/bubbleSortLinkedlist.js)

Screenshot:

![image](https://github.com/sudheerj/datastructures-algorithms/assets/10176547/fffb82a8-172c-4c0a-b4c0-53bce5c45ac0)

You may want, for example, to add links to the algorithms in the repo README like that:

---

**Bubble Sort**: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/sorting/bubbleSortLinkedlist.js) - [playground](https://livecodes.io/?console=open&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/sorting/bubbleSortLinkedlist.js)

---

LiveCodes also allows running [automated tests](https://livecodes.io/docs/features/tests/) (using Jest). This feature is used by TheAlgorithms website to validate the algorithms implementation.

Playgrounds can also be [embedded](https://livecodes.io/docs/features/embeds) in any webpage, using a powerful, yet easy-to-use, [SDK](https://livecodes.io/docs/sdk).

Comprehensive [documentations](https://livecodes.io/docs/) are available with live demos, code samples and screenshots.

LiveCodes is free with unlimited usage, no ads and no account required. It can be easily [self-hosted](https://livecodes.io/docs/features/self-hosting) (if you want), and can be used for commercial projects ([MIT license](https://livecodes.io/docs/license)).

Disclosure: obviously, I'm the author of LiveCodes.

If you feel this can be useful, I can help getting started with providing playgrounds for the code in this repo or for other projects.

I thought you would be interested. Otherwise, please feel free to close this.
Thank you.

**Comment by sudheerj** [comment]
@hatemhosny  Thank you for your words. I like LiveCodes playground for this repo. Can you assist with integrating playground?

**Comment by hatemhosny** [comment]
@sudheerj I'm glad you like LiveCodes.

LiveCodes can be used to demonstrate your code more than one way. These are examples that I quickly came up with:

- Embed a playground in a webpage that loads your code and run it.
  example: https://hatemhosny.github.io/datastructures-algorithms  
  ([edit in LiveCodes](https://livecodes.io/?activeEditor=script&x=https://github.com/hatemhosny/datastructures-algorithms/tree/gh-pages/src)) 

- Add links to playground e.g. in repo README

Example:

---

## JavaScript

array/containerWithMostWater: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/containerWithMostWater.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/containerWithMostWater.js)

array/containsDuplicate: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/containsDuplicate.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/containsDuplicate.js)

array/maxCircularSubArray: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/maxCircularSubArray.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/maxCircularSubArray.js)

array/maxProductSubArray: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/maxProductSubArray.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/maxProductSubArray.js)

array/maxSubArray: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/maxSubArray.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/maxSubArray.js)

array/minRotatedSortedArray: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/minRotatedSortedArray.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/minRotatedSortedArray.js)

array/productExceptSelf: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/productExceptSelf.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/productExceptSelf.js)

array/rotate: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/rotate.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/rotate.js)

array/searchRotatedSortedArray: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/searchRotatedSortedArray.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/searchRotatedSortedArray.js)

array/threeSum: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/threeSum.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/array/threeSum.js)

doublyLinkedlist/SwapNodePairs: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/doublyLinkedlist/SwapNodePairs.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/doublyLinkedlist/SwapNodePairs.js)

doublyLinkedlist/palindromeCheck: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/doublyLinkedlist/palindromeCheck.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/doublyLinkedlist/palindromeCheck.js)

doublyLinkedlist/swapFirstAndLast: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/doublyLinkedlist/swapFirstAndLast.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/doublyLinkedlist/swapFirstAndLast.js)

hashtable/duplicates: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/hashtable/duplicates.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/hashtable/duplicates.js)

hashtable/findTwoSumIndices: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/hashtable/findTwoSumIndices.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/hashtable/findTwoSumIndices.js)

hashtable/firstNonRepeatingCharacter: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/hashtable/firstNonRepeatingCharacter.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/hashtable/firstNonRepeatingCharacter.js)

hashtable/groupAnagrams: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/hashtable/groupAnagrams.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/hashtable/groupAnagrams.js)

hashtable/verifyCommonElements: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/hashtable/verifyCommonElements.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/hashtable/verifyCommonElements.js)

linkedlist/binaryToDecimal: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/binaryToDecimal.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/binaryToDecimal.js)

linkedlist/detectLoop: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/detectLoop.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/detectLoop.js)

linkedlist/findKthNodeFromEnd: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/findKthNodeFromEnd.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/findKthNodeFromEnd.js)

linkedlist/findMiddleNode: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/findMiddleNode.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/findMiddleNode.js)

linkedlist/partitionList: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/partitionList.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/partitionList.js)

linkedlist/removeDuplicates: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/removeDuplicates.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/removeDuplicates.js)

linkedlist/reverseSubstring: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/reverseSubstring.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/linkedlist/reverseSubstring.js)

queue/enqueueDequeueWithStacks: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/queue/enqueueDequeueWithStacks.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/queue/enqueueDequeueWithStacks.js)

sorting/bubbleSortLinkedlist: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/sorting/bubbleSortLinkedlist.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/sorting/bubbleSortLinkedlist.js)

sorting/mergeTwoSortedLists: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/sorting/mergeTwoSortedLists.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/sorting/mergeTwoSortedLists.js)

sorting/selectionSortLinkedlist: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/sorting/selectionSortLinkedlist.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/sorting/selectionSortLinkedlist.js)

stack/balancedBrackets: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/stack/balancedBrackets.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/stack/balancedBrackets.js)

stack/sortStack: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/stack/sortStack.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/stack/sortStack.js)

strings/greatestCommonDivisor: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/strings/greatestCommonDivisor.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/strings/greatestCommonDivisor.js)

strings/longestRepeatingCharReplacement: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/strings/longestRepeatingCharReplacement.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/strings/longestRepeatingCharReplacement.js)

strings/longestSubstringWithoutRepeatingChar: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/strings/longestSubstringWithoutRepeatingChar.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/strings/longestSubstringWithoutRepeatingChar.js)

strings/mergeStringsAlternately: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/strings/mergeStringsAlternately.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/strings/mergeStringsAlternately.js)

strings/minWindowSubstring: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/strings/minWindowSubstring.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/strings/minWindowSubstring.js)

strings/validAnagram: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/strings/validAnagram.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/algorithms/strings/validAnagram.js)

doublyLinkedlist/class/doublyLinkedlist: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/doublyLinkedlist/class/doublyLinkedlist.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/doublyLinkedlist/class/doublyLinkedlist.js)

doublyLinkedlist/class/node: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/doublyLinkedlist/class/node.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/doublyLinkedlist/class/node.js)

graphs/unweighted_undirected: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/graphs/unweighted_undirected.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/graphs/unweighted_undirected.js)

hashtable/hashtable: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/hashtable/hashtable.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/hashtable/hashtable.js)

linkedlist/Node: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/linkedlist/Node.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/linkedlist/Node.js)

linkedlist/class/linkedList: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/linkedlist/class/linkedList.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/linkedlist/class/linkedList.js)

linkedlist/class/node: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/linkedlist/class/node.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/linkedlist/class/node.js)

queue/queue_array: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/queue/queue_array.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/queue/queue_array.js)

queue/queue_with_linkedlist: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/queue/queue_with_linkedlist.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/queue/queue_with_linkedlist.js)

queue/queue_with_stacks: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/queue/queue_with_stacks.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/queue/queue_with_stacks.js)

stack/stack_with_array: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/stack/stack_with_array.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/stack/stack_with_array.js)

stack/stack_with_linkedlist: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/stack/stack_with_linkedlist.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/stack/stack_with_linkedlist.js)

trees/binary_search_tree: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/trees/binary_search_tree.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/trees/binary_search_tree.js)

bubbleSort/bubbleSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/bubbleSort/bubbleSort.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/bubbleSort/bubbleSort.js)

heapSort/heapSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/heapSort/heapSort.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/heapSort/heapSort.js)

insertionSort/insertionSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/insertionSort/insertionSort.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/insertionSort/insertionSort.js)

mergeSort/mergeSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/mergeSort/mergeSort.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/mergeSort/mergeSort.js)

quickSort/quickSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/quickSort/quickSort.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/quickSort/quickSort.js)

radixSort/radixSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/radixSort/radixSort.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/radixSort/radixSort.js)

selectionSort/selectionSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/selectionSort/selectionSort.js) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/sorting/selectionSort/selectionSort.js)

## Go

01-bubbleSort/BubbleSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/01-bubbleSort/BubbleSort.go) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/01-bubbleSort/BubbleSort.go)

02-selectionSort/SelectionSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/02-selectionSort/SelectionSort.go) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/02-selectionSort/SelectionSort.go)

03-insertionSort/InsertionSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/03-insertionSort/InsertionSort.go) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/03-insertionSort/InsertionSort.go)

04-mergeSort/MergeSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/04-mergeSort/MergeSort.go) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/04-mergeSort/MergeSort.go)

06-quickSort/QuickSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/06-quickSort/QuickSort.go) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/06-quickSort/QuickSort.go)

07-heapSort/HeapSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/07-heapSort/HeapSort.go) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/07-heapSort/HeapSort.go)

08-radixSort/RadixSort: [implementation](https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/08-radixSort/RadixSort.go) - [playground](https://livecodes.io/?console&x=https://github.com/sudheerj/datastructures-algorithms/blob/master/src/go/sorting/08-radixSort/RadixSort.go)

---

Please let me know what you think.

**Comment by sudheerj** [comment]
@hatemhosny  Thank you for the details. Do you support Java language as well? Also, how do we show if an algorithm exists in multiple files?

**Comment by hatemhosny** [comment]
Hello @sudheerj 

> Do you support Java language as well? 

Currently, Java is not "yet" supported, because I'm not able to compile/run Java in the browser (which is a requirement for any language to be supported by LiveCodes, being a client-side only app). See this issue for details: https://github.com/live-codes/livecodes/issues/516#issuecomment-1962798785

> Also, how do we show if an algorithm exists in multiple files?

Code running in LiveCodes needs to be loaded in the editors. Depending on the language, this can be done differently. However, in JavaScript/TypeScript, modules can be imported from various sources (e.g. npm, deno, jsr, GitHub, custom modules). See docs for details:
https://livecodes.io/docs/features/module-resolution.

May be I can help more if you have specific examples.

**Comment by sudheerj** [comment]
Okay. Got it. I mean if some of the files like node.js exists in a separate file. For example, https://github.com/sudheerj/datastructures-algorithms/tree/master/src/javascript/datastructures/linkedlist

**Comment by hatemhosny** [comment]
You can just import from the GitHub URL, like this:

```js
import Node from 'https://github.com/sudheerj/datastructures-algorithms/blob/master/src/javascript/datastructures/linkedlist/Node.js';

const node = new Node('hello');
console.log(node.toString());
```

[open in LiveCodes](https://livecodes.io/?x=id/v4gqhny2rq3)

If you do not want to show the full URL in code and instead use an alias (e.g. './Node'), you can use [custom import maps](https://livecodes.io/docs/features/module-resolution/#custom-module-resolution), to map this alias to a [CDN-provided URL](https://www.jsdelivr.com/?docs=gh) to your file like this:

Use this as custom settings (App menu -> Custom Settings)

```json
{
  "imports": {
    "./Node": "https://cdn.jsdelivr.net/gh/sudheerj/datastructures-algorithms@master/src/javascript/datastructures/linkedlist/Node.js"
  }
}
```
Then this code should work:

```js
import Node from './Node';

const node = new Node('hello');
console.log(node.toString());
```

[open in LiveCodes](https://livecodes.io/?x=id/h3334zy6ixy)

If you need to embed this playground in a web page, there is an advanced [SDK](https://livecodes.io/docs/sdk) (available in JS/TS, react, vue and svelte), that allows you to specify all the configurations you need and even communicate with the running playground. 

I hope this answers your question. Please let me know if you have any other questions or comments.

**Comment by hatemhosny** [comment]
> Do you support Java language as well?

hi @sudheerj 

We have recently added support for Java in LiveCodes using a JVM running in the browser.

Check demo:
https://livecodes.io/?x=id/mvtfmgnge4k

It is currently running Java 8, so more recent features will not work.
However, most of the code on your repo will probably work.

Please give it a try and let me know what you think.
