### ISSUE TITLE
Typo in the README.md

### ISSUE THREAD

**Issue by mademoiselle-chantal** [sudheerj/datastructures-algorithms#4]
**Description**

As l was reading through the README, l came across the typo "Strctures".

<img width="909" alt="Screenshot 2024-05-28 at 08 16 52" src="https://github.com/sudheerj/datastructures-algorithms/assets/120084609/9dc8c5ff-830b-4704-8f92-c1df5b30aee8">

**Comment by mademoiselle-chantal** [comment]
@sudheerj the PR for this issue is ready.

**Comment by sudheerj** [comment]
Merged. Thanks
